name: Create Production Builds

on:
  push:
    branches: ['beta']

jobs:
  build_android:
    name: Build Android
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: production
  build_ios:
    name: Build iOS
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
      profile: production
      
  submit_ios:
    name: Submit to Apple App Store
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      build_id: ${{ needs.build_ios.outputs.build_id }}
